.TH CHROME-SIP-LOGGER 1 "September 2026" "0.1.0" "chromeSIPLogger Manual"
.SH NAME
chrome-sip-logger \- Parse, store and rotate SIP logs from Odoo
.SH SYNOPSIS
.B chrome-sip-logger
.SH DESCRIPTION
.B chrome-sip-logger
is an automated background script executed hourly by systemd. 
It filters the google-chrome log stream to preserve only the Odoo Softphone SIP console logs, and purges the rest to save disk space.
.SH FILES
.I /usr/bin/chrome-sip-logger
.RS
The executable script.
.RE
.SH AUTHORS
haall <haall@odoo.com>