#!/usr/bin/python3

from datetime import datetime, timezone
from pathlib import Path

LOG_DIR: Path = Path("/var/log/chrome-sip-logger")
RAW_LOG_PATH = Path("/home/odoo/.config/google-chrome/chrome_debug.log")

class Extractor:
    def __init__(self, raw_log_path: Path = RAW_LOG_PATH, destination_log_path: Path = LOG_DIR):
        self.raw_log_path = raw_log_path
        date = datetime.now(tz=timezone.utc)
        self.destination_log_path = destination_log_path / f"{f"Y{date.year:04}_M{date.month:02}_D{date.day:02}_H{date.hour:02}_UTC"}.log"
        try:
            with open(self.destination_log_path, 'r') as file:
                file.close()
        except FileNotFoundError:
            with open(self.destination_log_path, 'w') as file:
                file.close()


class Writter():
    pass


class Rotater():
    pass

